---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cf-cs-sap-com-v1alpha1-clusterspace
  failurePolicy: Fail
  name: mclusterspace.kb.io
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterspaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cf-cs-sap-com-v1alpha1-servicebinding
  failurePolicy: Fail
  name: mservicebinding.kb.io
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicebindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cf-cs-sap-com-v1alpha1-serviceinstance
  failurePolicy: Fail
  name: mserviceinstance.kb.io
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceinstances
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cf-cs-sap-com-v1alpha1-space
  failurePolicy: Fail
  name: mspace.kb.io
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spaces
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cf-cs-sap-com-v1alpha1-clusterspace
  failurePolicy: Fail
  name: vclusterspace.kb.io
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterspaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cf-cs-sap-com-v1alpha1-servicebinding
  failurePolicy: Fail
  name: vservicebinding.kb.io
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicebindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cf-cs-sap-com-v1alpha1-serviceinstance
  failurePolicy: Fail
  name: vserviceinstance.kb.io
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceinstances
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cf-cs-sap-com-v1alpha1-space
  failurePolicy: Fail
  name: vspace.kb.io
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spaces
  sideEffects: None
