/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and cf-service-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/sap/cf-service-operator/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterSpaceLister helps list ClusterSpaces.
// All objects returned here must be treated as read-only.
type ClusterSpaceLister interface {
	// List lists all ClusterSpaces in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterSpace, err error)
	// Get retrieves the ClusterSpace from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ClusterSpace, error)
	ClusterSpaceListerExpansion
}

// clusterSpaceLister implements the ClusterSpaceLister interface.
type clusterSpaceLister struct {
	indexer cache.Indexer
}

// NewClusterSpaceLister returns a new ClusterSpaceLister.
func NewClusterSpaceLister(indexer cache.Indexer) ClusterSpaceLister {
	return &clusterSpaceLister{indexer: indexer}
}

// List lists all ClusterSpaces in the indexer.
func (s *clusterSpaceLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterSpace, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterSpace))
	})
	return ret, err
}

// Get retrieves the ClusterSpace from the index for a given name.
func (s *clusterSpaceLister) Get(name string) (*v1alpha1.ClusterSpace, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("clusterspace"), name)
	}
	return obj.(*v1alpha1.ClusterSpace), nil
}
