/*
SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and redis-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterSpaceListerExpansion allows custom methods to be added to
// ClusterSpaceLister.
type ClusterSpaceListerExpansion interface{}

// ServiceBindingListerExpansion allows custom methods to be added to
// ServiceBindingLister.
type ServiceBindingListerExpansion interface{}

// ServiceBindingNamespaceListerExpansion allows custom methods to be added to
// ServiceBindingNamespaceLister.
type ServiceBindingNamespaceListerExpansion interface{}

// ServiceInstanceListerExpansion allows custom methods to be added to
// ServiceInstanceLister.
type ServiceInstanceListerExpansion interface{}

// ServiceInstanceNamespaceListerExpansion allows custom methods to be added to
// ServiceInstanceNamespaceLister.
type ServiceInstanceNamespaceListerExpansion interface{}

// SpaceListerExpansion allows custom methods to be added to
// SpaceLister.
type SpaceListerExpansion interface{}

// SpaceNamespaceListerExpansion allows custom methods to be added to
// SpaceNamespaceLister.
type SpaceNamespaceListerExpansion interface{}
