/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and cf-service-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ClusterSpaceExpansion interface{}

type ServiceBindingExpansion interface{}

type ServiceInstanceExpansion interface{}

type SpaceExpansion interface{}
