/*
SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and cf-service-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	cfcssapcomv1alpha1 "github.com/sap/cf-service-operator/api/v1alpha1"
	versioned "github.com/sap/cf-service-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sap/cf-service-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/sap/cf-service-operator/pkg/client/listers/cf.cs.sap.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterSpaceInformer provides access to a shared informer and lister for
// ClusterSpaces.
type ClusterSpaceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterSpaceLister
}

type clusterSpaceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterSpaceInformer constructs a new informer for ClusterSpace type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterSpaceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterSpaceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterSpaceInformer constructs a new informer for ClusterSpace type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterSpaceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CfV1alpha1().ClusterSpaces().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CfV1alpha1().ClusterSpaces().Watch(context.TODO(), options)
			},
		},
		&cfcssapcomv1alpha1.ClusterSpace{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterSpaceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterSpaceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterSpaceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cfcssapcomv1alpha1.ClusterSpace{}, f.defaultInformer)
}

func (f *clusterSpaceInformer) Lister() v1alpha1.ClusterSpaceLister {
	return v1alpha1.NewClusterSpaceLister(f.Informer().GetIndexer())
}
