# permissions for end users to view clusterspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterspace-viewer-role
rules:
- apiGroups:
  - cf.cs.sap.com
  resources:
  - clusterspaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cf.cs.sap.com
  resources:
  - clusterspaces/status
  verbs:
  - get
