#!/bin/bash

set -eo pipefail

BASEDIR=$(realpath $(dirname "$0")/..)

rm -rf "$BASEDIR"/tmp
mkdir -p "$BASEDIR"/tmp/apis/cf.cs.sap.com

ln -s "$BASEDIR"/api/v1alpha1 "$BASEDIR"/tmp/apis/cf.cs.sap.com/v1alpha1

"$BASEDIR"/bin/client-gen \
  --clientset-name versioned \
  --input-base "" \
  --input github.com/sap/cf-service-operator/tmp/apis/cf.cs.sap.com/v1alpha1 \
  --go-header-file "$BASEDIR"/hack/boilerplate.go.txt \
  --output-package github.com/sap/cf-service-operator/pkg/client/clientset \
  --output-base "$BASEDIR"/tmp/pkg/client

"$BASEDIR"/bin/lister-gen \
  --input-dirs github.com/sap/cf-service-operator/tmp/apis/cf.cs.sap.com/v1alpha1 \
  --go-header-file "$BASEDIR"/hack/boilerplate.go.txt \
  --output-package github.com/sap/cf-service-operator/pkg/client/listers \
  --output-base "$BASEDIR"/tmp/pkg/client

"$BASEDIR"/bin/informer-gen \
  --input-dirs github.com/sap/cf-service-operator/tmp/apis/cf.cs.sap.com/v1alpha1 \
  --versioned-clientset-package github.com/sap/cf-service-operator/pkg/client/clientset/versioned \
  --listers-package github.com/sap/cf-service-operator/pkg/client/listers \
  --go-header-file "$BASEDIR"/hack/boilerplate.go.txt \
  --output-package github.com/sap/cf-service-operator/pkg/client/informers \
  --output-base "$BASEDIR"/tmp/pkg/client

find "$BASEDIR"/tmp/pkg/client -name "*.go" -exec \
  perl -pi -e "s#github\.com/sap/cf-service-operator/tmp/apis/cf\.cs\.sap\.com/v1alpha1#github\.com/sap/cf-service-operator/api/v1alpha1#g" \
  {} +

rm -rf "$BASEDIR"/pkg/client
mv "$BASEDIR"/tmp/pkg/client/github.com/sap/cf-service-operator/pkg/client "$BASEDIR"/pkg

rm -rf "$BASEDIR"/tmp

go fmt "$BASEDIR"/pkg/client/...
go vet "$BASEDIR"/pkg/client/...

