---
apiVersion: v1
kind: Service
metadata:
  name: cf-service-operator-webhook
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 2443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cf-service-operator-webhook
  namespace: default
subsets:
- addresses:
  - ip: ${HOST_IP}
  ports:
  - port: 2443
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cf-service-operator-webhook
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cf-service-operator-webhook
  namespace: default
spec:
  dnsNames:
  - cf-service-operator-webhook
  - cf-service-operator-webhook.default
  - cf-service-operator-webhook.default.svc
  - cf-service-operator-webhook.default.svc.cluster.local
  issuerRef:
    name: cf-service-operator-webhook
  secretName: cf-service-operator-webhook
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cf-service-operator-webhook
  annotations:
    cert-manager.io/inject-ca-from: default/cf-service-operator-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cf-service-operator-webhook
      namespace: default
      path: /mutate-cf-cs-sap-com-v1alpha1-clusterspace
      port: 443
  name: mutate.clusterspaces.cf.cs.sap.com
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterspaces
    scope: Cluster
  matchPolicy: Equivalent
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
  reinvocationPolicy: Never
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cf-service-operator-webhook
      namespace: default
      path: /mutate-cf-cs-sap-com-v1alpha1-space
      port: 443
  name: mutate.spaces.cf.cs.sap.com
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spaces
    scope: Namespaced
  matchPolicy: Equivalent
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
  reinvocationPolicy: Never
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cf-service-operator-webhook
      namespace: default
      path: /mutate-cf-cs-sap-com-v1alpha1-serviceinstance
      port: 443
  name: mutate.serviceinstances.cf.cs.sap.com
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceinstances
    scope: Namespaced
  matchPolicy: Equivalent
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
  reinvocationPolicy: Never
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cf-service-operator-webhook
      namespace: default
      path: /mutate-cf-cs-sap-com-v1alpha1-servicebinding
      port: 443
  name: mutate.servicebindings.cf.cs.sap.com
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicebindings
    scope: Namespaced
  matchPolicy: Equivalent
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
  reinvocationPolicy: Never
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cf-service-operator-webhook
  annotations:
    cert-manager.io/inject-ca-from: default/cf-service-operator-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cf-service-operator-webhook
      namespace: default
      path: /validate-cf-cs-sap-com-v1alpha1-clusterspace
      port: 443
  name: validate.clusterspaces.cf.cs.sap.com
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clusterspaces
    scope: Cluster
  matchPolicy: Equivalent
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cf-service-operator-webhook
      namespace: default
      path: /validate-cf-cs-sap-com-v1alpha1-space
      port: 443
  name: validate.spaces.cf.cs.sap.com
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - spaces
    scope: Namespaced
  matchPolicy: Equivalent
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cf-service-operator-webhook
      namespace: default
      path: /validate-cf-cs-sap-com-v1alpha1-serviceinstance
      port: 443
  name: validate.serviceinstances.cf.cs.sap.com
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - serviceinstances
    scope: Namespaced
  matchPolicy: Equivalent
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cf-service-operator-webhook
      namespace: default
      path: /validate-cf-cs-sap-com-v1alpha1-servicebinding
      port: 443
  name: validate.servicebindings.cf.cs.sap.com
  rules:
  - apiGroups:
    - cf.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - servicebindings
    scope: Namespaced
  matchPolicy: Equivalent
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
