/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cf-service-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/sap/cf-service-operator/pkg/client/clientset/versioned/typed/cf.cs.sap.com/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCfV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCfV1alpha1) ClusterSpaces() v1alpha1.ClusterSpaceInterface {
	return &FakeClusterSpaces{c}
}

func (c *FakeCfV1alpha1) ServiceBindings(namespace string) v1alpha1.ServiceBindingInterface {
	return &FakeServiceBindings{c, namespace}
}

func (c *FakeCfV1alpha1) ServiceInstances(namespace string) v1alpha1.ServiceInstanceInterface {
	return &FakeServiceInstances{c, namespace}
}

func (c *FakeCfV1alpha1) Spaces(namespace string) v1alpha1.SpaceInterface {
	return &FakeSpaces{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCfV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
