# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/cf.cs.sap.com_spaces.yaml
- bases/cf.cs.sap.com_clusterspaces.yaml
- bases/cf.cs.sap.com_serviceinstances.yaml
- bases/cf.cs.sap.com_servicebindings.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_spaces.yaml
#- patches/webhook_in_clusterspaces.yaml
#- patches/webhook_in_serviceinstances.yaml
#- patches/webhook_in_servicebindings.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_spaces.yaml
#- patches/cainjection_in_clusterspaces.yaml
#- patches/cainjection_in_serviceinstances.yaml
#- patches/cainjection_in_servicebindings.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
